#!/bin/bash

################################################################################
# SearXNG 一键部署脚本
# 用途: 自动部署本地 SearXNG 实例，配置完成后即可使用
################################################################################

set -e  # 遇到错误立即退出

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 配置
SEARXNG_DIR="${HOME}/searxng-local"
SEARXNG_PORT="${SEARXNG_PORT:-8080}"
CHATBOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

################################################################################
# 辅助函数
################################################################################

print_header() {
    echo ""
    echo -e "${BLUE}================================================================${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}================================================================${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

check_command() {
    if ! command -v $1 &> /dev/null; then
        print_error "$1 未安装，请先安装 $1"
        exit 1
    fi
}

################################################################################
# 主要功能
################################################################################

# 1. 检查依赖
check_dependencies() {
    print_header "检查系统依赖"
    
    check_command docker
    print_success "Docker 已安装"
    
    # 检查 Docker Compose (优先使用内置版本)
    if docker compose version &> /dev/null; then
        COMPOSE_CMD="docker compose"
        print_success "Docker Compose 已安装 (使用内置版本)"
    elif command -v docker-compose &> /dev/null; then
        COMPOSE_CMD="docker-compose"
        print_success "Docker Compose 已安装 (使用独立版本)"
    else
        print_error "Docker Compose 未安装"
        exit 1
    fi
    
    # 检查 Docker 是否运行
    if ! docker info &> /dev/null; then
        print_error "Docker 未运行，请先启动 Docker Desktop"
        exit 1
    fi
    print_success "Docker 服务正在运行"
    
    # 检查端口是否被占用
    if lsof -Pi :${SEARXNG_PORT} -sTCP:LISTEN -t >/dev/null 2>&1; then
        print_warning "端口 ${SEARXNG_PORT} 已被占用"
        read -p "是否使用其他端口？(输入新端口号，或按回车取消): " NEW_PORT
        if [ ! -z "$NEW_PORT" ]; then
            SEARXNG_PORT=$NEW_PORT
            print_info "将使用端口: ${SEARXNG_PORT}"
        else
            print_error "部署取消"
            exit 1
        fi
    fi
}

# 2. 创建部署目录
create_directory() {
    print_header "创建部署目录"
    
    if [ -d "$SEARXNG_DIR" ]; then
        print_warning "目录 $SEARXNG_DIR 已存在"
        read -p "是否删除并重新创建？(y/N): " CONFIRM
        if [ "$CONFIRM" = "y" ] || [ "$CONFIRM" = "Y" ]; then
            rm -rf "$SEARXNG_DIR"
            print_info "已删除旧目录"
        else
            print_info "将使用现有目录"
        fi
    fi
    
    mkdir -p "$SEARXNG_DIR"
    mkdir -p "$SEARXNG_DIR/searxng-data"
    print_success "目录创建完成: $SEARXNG_DIR"
}

# 3. 生成配置文件
generate_configs() {
    print_header "生成配置文件"
    
    # 生成 secret key
    SECRET_KEY=$(python3 -c 'import os; print(os.urandom(24).hex())' 2>/dev/null || openssl rand -hex 24)
    print_success "生成 secret key: ${SECRET_KEY:0:20}..."
    
    # 创建 docker-compose.yml
    cat > "$SEARXNG_DIR/docker-compose.yml" <<EOF
version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "${SEARXNG_PORT}:8080"
    volumes:
      - ./searxng-data:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:${SEARXNG_PORT}/
      - SEARXNG_PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
EOF
    print_success "创建 docker-compose.yml"
    
    # 创建 settings.yml (使用最小化但完整的配置)
    cat > "$SEARXNG_DIR/searxng-data/settings.yml" <<'EOF'
# SearXNG Configuration for AI Agent
# Auto-generated by deploy-searxng.sh
# Minimal but complete configuration

use_default_settings: true

general:
  instance_name: "AI Agent Local SearXNG"
  enable_metrics: false

server:
  secret_key: "SECRET_KEY_PLACEHOLDER"
  limiter: false
  image_proxy: true
  
search:
  safe_search: 1
  autocomplete: ""
  default_lang: "auto"
  formats:
    - html
    - json

ui:
  static_use_hash: true

outgoing:
  request_timeout: 3.0
  max_request_timeout: 10.0
  
enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
EOF
    
    # 替换 secret key
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|SECRET_KEY_PLACEHOLDER|${SECRET_KEY}|" "$SEARXNG_DIR/searxng-data/settings.yml"
    else
        sed -i "s|SECRET_KEY_PLACEHOLDER|${SECRET_KEY}|" "$SEARXNG_DIR/searxng-data/settings.yml"
    fi
    print_success "创建 settings.yml"
}

# 4. 启动 SearXNG
start_searxng() {
    print_header "启动 SearXNG 服务"
    
    cd "$SEARXNG_DIR"
    
    # 检查是否已有运行的容器
    if docker ps -a --format '{{.Names}}' | grep -q '^searxng$'; then
        print_warning "检测到已存在的 searxng 容器"
        docker stop searxng 2>/dev/null || true
        docker rm searxng 2>/dev/null || true
        print_info "已清理旧容器"
    fi
    
    # 启动服务
    print_info "正在启动 SearXNG 容器..."
    $COMPOSE_CMD up -d
    
    print_success "SearXNG 容器已启动"
    
    # 等待服务就绪
    print_info "等待服务启动 (最多等待 60 秒)..."
    for i in {1..60}; do
        if curl -s "http://localhost:${SEARXNG_PORT}" > /dev/null 2>&1; then
            print_success "SearXNG 服务已就绪！"
            return 0
        fi
        echo -n "."
        sleep 1
    done
    
    print_warning "服务启动超时，请检查日志: docker logs searxng"
}

# 5. 验证部署
verify_deployment() {
    print_header "验证部署"
    
    # 检查容器状态
    if ! docker ps --format '{{.Names}}' | grep -q '^searxng$'; then
        print_error "容器未运行"
        print_info "查看日志: docker logs searxng"
        return 1
    fi
    print_success "容器运行中"
    
    # 检查 Web 界面
    print_info "检查 Web 界面..."
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:${SEARXNG_PORT}")
    if [ "$HTTP_CODE" = "200" ]; then
        print_success "Web 界面可访问: http://localhost:${SEARXNG_PORT}"
    else
        print_error "Web 界面不可访问 (HTTP $HTTP_CODE)"
        return 1
    fi
    
    # 检查 JSON API
    print_info "检查 JSON API..."
    API_RESPONSE=$(curl -s "http://localhost:${SEARXNG_PORT}/search?q=test&format=json")
    if echo "$API_RESPONSE" | grep -q '"results"'; then
        RESULT_COUNT=$(echo "$API_RESPONSE" | grep -o '"results"' | wc -l)
        print_success "JSON API 工作正常 (测试搜索返回结果)"
    else
        print_error "JSON API 不可用"
        print_info "响应内容: ${API_RESPONSE:0:200}"
        return 1
    fi
    
    print_success "所有检查通过！✨"
}

# 6. 配置 AI Agent
configure_ai_agent() {
    print_header "配置 AI Agent"
    
    cd "$CHATBOT_DIR"
    
    # 检查 .env 文件
    if [ ! -f .env ]; then
        if [ -f .env.example ]; then
            cp .env.example .env
            print_info "已从 .env.example 创建 .env 文件"
        else
            print_warning ".env 文件不存在，请手动创建"
            return 1
        fi
    fi
    
    # 更新 SEARXNG_URL
    if grep -q "^SEARXNG_URL=" .env; then
        # 更新现有配置
        if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS
            sed -i '' "s|^SEARXNG_URL=.*|SEARXNG_URL=http://localhost:${SEARXNG_PORT}|" .env
        else
            # Linux
            sed -i "s|^SEARXNG_URL=.*|SEARXNG_URL=http://localhost:${SEARXNG_PORT}|" .env
        fi
        print_success "已更新 SEARXNG_URL"
    else
        # 添加新配置
        echo "SEARXNG_URL=http://localhost:${SEARXNG_PORT}" >> .env
        print_success "已添加 SEARXNG_URL"
    fi
    
    # 更新 SEARCH_ENABLED
    if grep -q "^SEARCH_ENABLED=" .env; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^SEARCH_ENABLED=.*|SEARCH_ENABLED=true|" .env
        else
            sed -i "s|^SEARCH_ENABLED=.*|SEARCH_ENABLED=true|" .env
        fi
        print_success "已启用搜索功能"
    else
        echo "SEARCH_ENABLED=true" >> .env
        print_success "已启用搜索功能"
    fi
}

# 7. 显示完成信息
show_completion() {
    print_header "🎉 部署完成！"
    
    echo ""
    echo -e "${GREEN}SearXNG 已成功部署并运行！${NC}"
    echo ""
    echo -e "${BLUE}📍 服务地址:${NC}"
    echo "   Web 界面: http://localhost:${SEARXNG_PORT}"
    echo "   API 地址: http://localhost:${SEARXNG_PORT}/search?q=test&format=json"
    echo ""
    echo -e "${BLUE}📁 部署目录:${NC}"
    echo "   $SEARXNG_DIR"
    echo ""
    echo -e "${BLUE}🔧 常用命令:${NC}"
    echo "   查看状态: docker ps -f name=searxng"
    echo "   查看日志: docker logs searxng -f"
    echo "   停止服务: docker stop searxng"
    echo "   启动服务: docker start searxng"
    echo "   重启服务: docker restart searxng"
    echo ""
    echo -e "${BLUE}🚀 下一步:${NC}"
    echo "   1. 启动 AI Agent: chainlit run app.py"
    echo "   2. 在聊天界面使用: /search on"
    echo "   3. 或使用一键启动脚本: ./start-all.sh"
    echo ""
    echo -e "${YELLOW}💡 提示:${NC}"
    echo "   - 配置文件: $SEARXNG_DIR/searxng-data/settings.yml"
    echo "   - 可以自定义搜索引擎和参数"
    echo "   - 故障排查: docs/guides/troubleshooting/searxng.md"
    echo ""
}

################################################################################
# 主流程
################################################################################

main() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║                                                                ║${NC}"
    echo -e "${BLUE}║          🚀 SearXNG 一键部署脚本 v1.0                         ║${NC}"
    echo -e "${BLUE}║          为 AI Agent 提供本地搜索服务                         ║${NC}"
    echo -e "${BLUE}║                                                                ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    check_dependencies
    create_directory
    generate_configs
    start_searxng
    
    if verify_deployment; then
        configure_ai_agent
        show_completion
        exit 0
    else
        print_error "部署验证失败，请检查日志"
        print_info "查看日志: docker logs searxng"
        exit 1
    fi
}

# 执行主流程
main "$@"

